---
- set_fact:
    docker_ee_subscriptions_sles: "{{hostvars['localhost']['docker_ee_subscriptions_sles']}}"
    docker_ucp_license_path: "./docker-ee-sles.lic"
  when: hostvars['localhost']['docker_ee_subscriptions_sles'] is defined
