---
- name: "Install required NFS dependencies (Ubuntu)."
  when: ansible_distribution == 'Ubuntu'
  block:
  - name: "Install nfs-common."
    apt:
      name: "nfs-common"
      state: present
  - service:
      name: "rpcbind"
      state: "started"
      enabled: true
  - service:
      name: "rpc-statd"
      state: "started"
      enabled: true
