---
- set_fact:
    docker_ee_subscriptions_oracle: "{{hostvars['localhost']['docker_ee_subscriptions_oracle']}}"
    docker_ucp_license_path: "./docker-ee-oracle.lic"
  when: hostvars['localhost']['docker_ee_subscriptions_oracle'] is defined
