---
- set_fact:
    docker_ee_subscriptions_redhat: "{{hostvars['localhost']['docker_ee_subscriptions_rhel']}}"
    docker_ucp_license_path: "./docker-ee-rhel.lic"
  when: hostvars['localhost']['docker_ee_subscriptions_rhel'] is defined
