---
- name: "Installation ({{ ansible_os_family }})."
  include_tasks: "{{ os_family }}.yml"
  when: ansible_os_family == os_family
  with_items:
    - "RedHat"
    - "Windows"
  loop_control:
    loop_var: os_family
