---
#
# Modes.
#
- name: "Install."
  include_tasks: "install/main.yml"
  when: docker_ce_role_mode == "install"

- name: "Uninstall."
  include_tasks: "uninstall/main.yml"
  when: docker_ce_role_mode == "uninstall"

- name: "Update."
  include_tasks: "update/main.yml"
  when: docker_ce_role_mode == "update"

- name: "Logs."
  include_tasks: "logs/main.yml"
  when: docker_ce_role_mode == "logs"
